version: 0.2
phases:
 install:
  runtime-versions:
   python: 3.7
 build: 
  commands:
   - sam build
   - export BUCKET1=backend-bucket-smartalbum
   - sam package --template-file template.yml --s3-bucket $BUCKET1 --output-template-file outputTemplate.yml
artifacts:
 type: zip
 files:
  - template.yml
  - outputTemplate.yml