AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  LambdaFunction1:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: search-photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./Lambda
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::164394037047:role/service-role/search-photos-role-fcdmji0t'
      Environment:
        Variables:
          REGION: us-east-1
      Events:
        APIGatewayTrigger:
          Type: 'AWS::ApiGateway::RestApi'
          Properties:
            Name : RestApiPhotoAlbum
      Environment:
        Variables:
          REGION: us-east-1
  LambdaFunction2:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: index-photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./Lambda
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::164394037047:role/service-role/index-photos-role-mtlmnhgd'
      Events:
        S3Trigger:
          Type: S3
          Properties:
            Bucket:
              Ref: backend-bucket-smartalbum
            Events: s3:ObjectCreated:Put
      Environment:
        Variables:
          REGION: us-east-1