AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: Python file including external library
  Resources:
    LambdaFunction1:
      Type: AWS::Serverless::Function
      Properties:
        Handler: lambda_function.lambda_handler
        Runtime: python3.7
        FunctionName: search-photos
        CodeUri: ./Lambda #Directory the source file is
    LambdaFunction2:
      Type: AWS::Serverless::Function
      Properties:
        Handler: lambda_function.lambda_handler
        Runtime: python3.7
        FunctionName: index-photos
        CodeUri: ./Lambda #Directory the source file is